### ISSUE TITLE
Create a secret and put all environment variables 

### ISSUE THREAD

**Issue by fsadykov** [fuchicorp/academy#207]
Hello @bkarakas,

We are facing some security issues with academy. Everyone able to see all credentials and we have to move them to secret and restrict people to see that credentials. Please create a terraform code and make sure the secret is created and put in this location `academy/deployments/terraform`. Every time when we deployed secret should be referenced in the helm chart see bellow code.

```
globalEnvironments:
  enabled: true
  environments:

  - name: MYSQL_USER
    value: ${mysql_user}

  - name: MYSQL_DATABASE
    value: ${mysql_database}

  - name: MYSQL_PASSWORD
    value: ${mysql_password}

```
